#!/bin/bash

rm -f build.log

echo Building game library ...
make -C gamelib &> build.log.tmp
cat build.log.tmp >> build.log
rm -f build.log.tmp
if [ ! -f gamelib/libgame.a ]; then
   echo Game library compilation failed. 
   echo See build.log for errors.
   exit
fi

echo Building tools ...
cd tools
compile &> build.log.tmp
cat build.log.tmp >> build.log
rm -f build.log.tmp
cd ..

echo Building GJID executable ...
make -C src &> build.log.tmp
cat build.log.tmp >> build.log
rm -f build.log.tmp

if [ ! -f src/gjid ]; then
   echo GJID compilation failed. 
   echo See build.log for errors.
   exit
fi

echo Building data file ...
cd src 
mkdata &> build.log.tmp
cat build.log.tmp >> build.log
rm -f build.log.tmp
cd ..
if [ ! -f src/gjid.dat ]; then
   echo GJID compilation failed. 
   exit
fi

echo --
echo Finished building. Log in build.log
echo Now suid root and run \'make -C src install\'
echo After you\'ve done that, run \'gjid\' to start the game.
echo

