#!/bin/sh
#########################################################################
## Strip the levels out of the old gjid.dat and place them in gjid.levels
## Note: it uses gjid.size, where mkdata recorded the end of all the pics
#########################################################################

if [ -f gjid.dat ]; then
    echo Saving old levels ...
    if [ -f gjid.size ]; then
       SIZE=`ls -l gjid.dat | awk '{print $5;}'`
       OLDSIZE=`cat gjid.size`
       LEVELSIZE=`expr $SIZE - $OLDSIZE`
       echo Size changed from $OLDSIZE to $SIZE - $LEVELSIZE in levels
       tail -c $LEVELSIZE gjid.dat > gjid.levels
    else
       echo gjid.size not found. Levels cannot be recovered.
    fi
else
    echo Could not find gjid.dat
fi

