/* ascii.h
**	Generated by getascii. Lists key codes.
*/

#ifndef __ASCII_H
#define __ASCII_H

#define KEY_ESC			27
#define KEY_F1			274
#define KEY_F2			275
#define KEY_F3			276
#define KEY_F4			277
#define KEY_F5			278
#define KEY_F6			348
#define KEY_F7			349
#define KEY_F8			350
#define KEY_F9			342
#define KEY_F10			343
#define KEY_F11			345
#define KEY_F12			346
#define KEY_TAB			9
#define KEY_ENTER		10
#define KEY_INS			294
#define KEY_DEL			295
#define KEY_HOME		293
#define KEY_END			296
#define KEY_PGUP		297
#define KEY_PGDN		298
#define KEY_LEFT		186
#define KEY_RIGHT		185
#define KEY_UP			183
#define KEY_DOWN		184
#define KEY_BACKSPACE		127
#define KEY_SPACE		32

#endif

