#!/bin/bash

CC=g++
CFLAGS="-Wall -W -Werror -I../include -L../gamelib -DFB_GR"
LIBS="-lgame"

for i in *.cc; do
    EXE=${i%%.cc}
    if [ ! -f $EXE ]; then
	echo Compiling $i ...
	$CC $CFLAGS -o $EXE $i $LIBS
	strip $EXE
    elif [ $i -nt $EXE ] || [ ${1:-"none"} = $EXE ]; then
	echo Rebuilding $i ...
	rm -f $EXE
	$CC $CFLAGS -o $EXE $i $LIBS
	strip $EXE
    fi
done

