#!/bin/sh

BINDIR=/home/mike/bin

echo Changing permissions to suid
chown root getascii grabpal 
chmod 4711 getascii grabpal

echo "Installing binaries in $BINDIR"
install -o root -m 4711 getascii grabpal $BINDIR
install -m 755 mkpal mkpix pixrotate $BINDIR
